import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {build} from 'esbuild';import {JSDOM} from 'jsdom';import {harness} from './harness.mjs';
const until=async fn=>{for(let i=0;i<250;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('UI timed out');};
const bundle=async file=>(await build({entryPoints:[new URL('../assets/'+file,import.meta.url).pathname],bundle:true,write:false,format:'iife',globalName:'MembershipUI'})).outputFiles[0].text;
test('member booking form and admin approval work with actual SQL and API',async()=>{
 const h=await harness(),ok=async(a,p={},s)=>{const r=await h.call(a,p,s);assert.equal(r.status,200,JSON.stringify(r.data));return r.data;},password='Preview!Safe2026';
 await ok('register',{linkToken:await h.bootstrap(),username:'slowsix',password,name:'관리자'});const admin=(await ok('login',{username:'slowsix',password})).sessionToken;
 const link=await ok('member_invite',{tier:'friends'},admin);await ok('register',{linkToken:link.url.split('=')[1],username:'friend',password,name:'친구',gender:'여성',age_group:'30대',purposes:['보드게임']});const pending=(await ok('member_people',{},admin)).items.find(x=>x.username==='friend');await ok('member_person_save',{id:pending.id,version:pending.version,tier:'friends',status:'active'},admin);const member=(await ok('login',{username:'friend',password})).sessionToken;
 const dom=new JSDOM(await readFile(new URL('../membership.html',import.meta.url),'utf8'),{url:'https://slowsixon.com/membership.html',runScripts:'outside-only'}),w=dom.window,$=id=>w.document.getElementById(id);w.crypto.randomUUID=()=>crypto.randomUUID();w.AbortController=AbortController;w.localStorage.setItem('ss-member-session',member);w.confirm=()=>true;
 w.fetch=async(url,opts)=>{const b=JSON.parse(opts.body),r=await h.call(b.action,b,b.sessionToken);return new Response(JSON.stringify(r.data),{status:r.status});};
 let ad;
 try{
  w.eval(await bundle('membership.js'));await until(()=>$('booking-calendar').children.length>7);assert.equal($('member-tier').textContent,'슬로우식스 프렌즈');assert.match($('coupon-balance').textContent,/1\/1/);
  const date=new Date(Date.now()+3*86400000+9*3600000).toISOString().slice(0,10);$('booking-date').value=date;$('booking-coupon').checked=true;$('booking-form').dispatchEvent(new w.Event('input'));assert.match($('booking-breakdown').textContent,/12%/);assert.match($('booking-breakdown').textContent,/쿠폰 3,000원/);
  $('booking-form').dispatchEvent(new w.Event('submit',{cancelable:true}));await until(()=>$('my-bookings').textContent.includes('예약 요청'));assert.match($('coupon-balance').textContent,/0\/1/);assert.equal($('booking-coupon').disabled,true);
  const approvalLink=await ok('member_invite',{tier:'friends'},admin);await ok('register',{linkToken:approvalLink.url.split('=')[1],username:'newfriend',password,name:'새 친구',gender:'남성',age_group:'20대',purposes:['보드게임']});
  ad=new JSDOM('<div id="root"></div>',{url:'https://slowsixon.com/admin.html',runScripts:'outside-only'});ad.window.confirm=()=>true;ad.window.eval(await bundle('membership-admin.js'));let notice='';const panel=ad.window.MembershipUI.mountMembershipAdmin(ad.window.document.getElementById('root'),(a,p)=>ok(a,p,admin),m=>notice=m);await panel.load();const approve=Array.from(ad.window.document.querySelectorAll('#ma-people button')).find(b=>b.textContent==='가입 승인');assert.ok(approve);approve.click();await until(()=>notice.includes('가입을 승인했습니다'));assert.equal((await ok('login',{username:'newfriend',password})).user.status,'active');
  const inbox=ad.window.document.getElementById('ma-inbox');assert.match(inbox.textContent,/친구/);inbox.querySelector('textarea').value='테스트은행 12345 · 예금주 슬로우식스';Array.from(inbox.querySelectorAll('button')).find(b=>b.textContent==='승인·입금 안내').click();await until(()=>notice==='예약 상태를 변경했습니다.'&&inbox.textContent.includes('입금 확인·예약 확정'));
  $('booking-refresh').click();await until(()=>$('my-bookings').textContent.includes('테스트은행 12345'));assert.match($('my-bookings').textContent,/입금 대기/);
  Array.from(inbox.querySelectorAll('button')).find(b=>b.textContent==='입금 확인·예약 확정').click();await until(()=>inbox.textContent.includes('처리할 예약이 없습니다'));
  $('booking-refresh').click();await until(()=>$('my-bookings').textContent.includes('예약 확정'));assert.equal($('my-bookings').querySelectorAll('button').length,0);
  assert.match($('member-notifications').textContent,/예약이 확정/);
 }finally{dom.window.close();ad?.window.close();await h.db.close();}
});
test('invitation form requires gender, age and at least one purpose',async()=>{
 const dom=new JSDOM(await readFile(new URL('../membership.html',import.meta.url),'utf8'),{url:'https://slowsixon.com/membership.html#invite='+'a'.repeat(64),runScripts:'outside-only'}),w=dom.window,$=id=>w.document.getElementById(id);
 w.crypto.randomUUID=()=>crypto.randomUUID();w.AbortController=AbortController;const actions=[];w.fetch=async(url,opts)=>{const b=JSON.parse(opts.body);actions.push(b.action);return new Response(JSON.stringify(b.action==='register'?{status:'pending'}:{kind:'member',tier:'friends'}),{status:200});};
 try{w.eval(await bundle('membership.js'));await until(()=>$('member-gender').required);$('member-username').value='example';$('member-password').value='Example!2026';$('member-confirm').value='Example!2026';$('member-nickname').value='친구';assert.equal($('member-auth-form').checkValidity(),false);$('member-gender').value='여성';$('member-age').value='30대';assert.equal($('member-auth-form').checkValidity(),false);const purpose=$('member-purposes').querySelector('input');purpose.checked=true;purpose.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal($('member-auth-form').checkValidity(),true);purpose.checked=false;purpose.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal($('member-auth-form').checkValidity(),false);purpose.checked=true;purpose.dispatchEvent(new w.Event('change',{bubbles:true}));$('member-auth-form').dispatchEvent(new w.Event('submit',{cancelable:true}));await until(()=>$('notice').textContent.includes('관리자 승인 후'));assert.equal(actions.includes('register'),true);assert.equal(actions.includes('login'),false);assert.equal(w.localStorage.getItem('ss-member-session'),null);}finally{w.close();}
});
